all:
	$(MAKE) -C "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk/build"
kissat:
	$(MAKE) -C "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk/build" kissat
tissat:
	$(MAKE) -C "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk/build" tissat
clean:
	rm -f "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk"/makefile
	-$(MAKE) -C "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk/build" clean
	rm -rf "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk/build"
coverage:
	$(MAKE) -C "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk/build" coverage
indent:
	$(MAKE) -C "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk/build" indent
test:
	$(MAKE) -C "/mnt/c/Users/alex/IdeaProjects/Tema2AA/src/Kissat_MAB-HyWalk/build" test
.PHONY: all clean coverage indent kissat test tissat
